<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1171610171437" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://www.tibco.com/schemas/AccountState/SharedResources/Schema.xsd" targetNamespace="http://xmlns.example.com/1171610171437">
    <documentation>Abstract WSDL resource for SOAP communication with GetAccountState process</documentation>
    <import namespace="http://www.tibco.com/schemas/AccountState/SharedResources/Schema.xsd" location="AccountsXSD.xsd"/>
    <message name="GetAccountStateServiceInputMessage">
        <part name="part1" element="ns:Name"/>
    </message>
    <message name="GetAccountStateServiceOutputMessage">
        <part name="part1" element="ns:Account"/>
    </message>
    <portType name="GetAccountStateServicePort">
        <operation name="GetAccountStateOperation">
            <input message="tns:GetAccountStateServiceInputMessage"/>
            <output message="tns:GetAccountStateServiceOutputMessage"/>
        </operation>
    </portType>
</definitions>